config, database: Add some debug logging
(With the occasional info logging, but the defaults should
suppress that, too; the log level needs to be lowered
to debug or info to see anything.)

Example:

    >>> import database
    >>> import config
    >>> import logging
    >>> logging.basicConfig(level=logging.DEBUG)
    >>> database.open_db()
    DEBUG:database:DB 0x7efce2516a58: Instantiating DB(path_prefix=PosixPath('.'))
    INFO:database:DB 0x7efce2516a58: Opening DB at: vectors.lmdb
    >>> config.open_db()
    DEBUG:config:ConfigDB 0x7efccd4f81d0: Instantiating ConfigDB(path_prefix=PosixPath('.'))
    INFO:config:ConfigDB 0x7efccd4f81d0: Opening DB at: config.lmdb
    DEBUG:config:ConfigDB 0x7efccd4f81d0: Loading tags...
    DEBUG:config:ConfigDB 0x7efccd4f81d0: Loading tag 'Austauschschülerin'
    DEBUG:database:DB 0x7efce2516a58: get_face(idx=b'\xb2\x02\x00\x00\x00\x00\x00\x00', face_idx=b'\x00\x00') -> face_key=b'\xb2\x02\x00\x00\x00\x00\x00\x00f\x00\x00'
    DEBUG:database:DB 0x7efce2516a58: ... raw_face=None
    Traceback (most recent call last):
    [...]
    TypeError: 'NoneType' object is not subscriptable
    >>> ^D
    DEBUG:database:DB 0x7efce2516a58: Closing DB
    DEBUG:config:ConfigDB 0x7efccd4f81d0: Closing DB